#!/usr/bin/env php
<?php
/**
 * 系统工具包,注意此工具包需要 Symfony2/Console、Doctrine2支持
 */
define('APPLICATION_ROOT', dirname(dirname(__FILE__)) .'/');

// 环境变量
define('ENVIRONMENT', 'prod');

// 加载 Illuminate\Console Doctrine Eloquent
require APPLICATION_ROOT . 'vendor/autoload.php';

// 加载 TradingMax 命令行工具
require APPLICATION_ROOT . 'application/third_party/TradingMax/autoload.php';


// 加载app
$app = new Symfony\Component\Console\Application('TradingMax 命令行工具', 'v1.0(stable)');
$app->setCatchExceptions(TRUE);
$app->setHelperSet($helperSet);


// 开始注册所需命令
$artisans = [
    // 队列命令
    new \Console\CreateJobCommand(),
    new \Console\WorkQueueCommand(),
    // new \Console\ListenCommand(),
    new \Console\ListFailedCommand(),
];

$app->addCommands($artisans);
$app->run();

exit(0);