#!/usr/bin/env php
<?php
/**
 * 系统工具包,注意此工具包需要 Symfony2/Console、Doctrine2支持
 */
// 项目根目录
define('ROOT_PATH', rtrim(__DIR__, '/') . DIRECTORY_SEPARATOR);


// 队列组件目录
define('LIB_PATH', rtrim(dirname(__FILE__) . '/src', '/') . DIRECTORY_SEPARATOR);

// 依赖组件目录
define('VENDOR_PATH', rtrim(dirname(__FILE__) . '/vendor', '/') . DIRECTORY_SEPARATOR);

// 定义应用的命名空间
define('APP_NAMESPACE', 'Queue');

// 设置时区
date_default_timezone_set('PRC');

// 环境变量
define('ENVIRONMENT', 'prod');

// 加载 Illuminate\Console
require VENDOR_PATH . 'autoload.php';

// 加载 redis-queue组件
require LIB_PATH . '/autoload.php';

// 加载 app
$app = new Symfony\Component\Console\Application('RedisQueue 命令行工具', 'v1.0(stable)');
$app->setCatchExceptions(true);
//$app->setHelperSet($helperSet);

// 开始注册所需命令
$artisans = [
    // 队列命令
    new \Console\CreateJobCommand(),
    new \Console\WorkQueueCommand(),
    new \Console\ListenCommand(),
    new \Console\ListFailedCommand(),
];
$app->addCommands($artisans);
$app->run();
exit(0);